/**
 * Application Constants
 */

export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  TENANT_ADMIN: 'TENANT_ADMIN',
  EMPLOYEE: 'EMPLOYEE'
};

export const ATTENDANCE_STATUS = {
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT',
  LATE: 'LATE',
  HALF_DAY: 'HALF_DAY'
};

export const LEAVE_REQUEST_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
};

export const LEAVE_REQUEST_TYPE = {
  ANNUAL: 'ANNUAL',
  SICK: 'SICK',
  PERSONAL: 'PERSONAL',
  UNPAID: 'UNPAID'
};

export const EMPLOYMENT_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  TERMINATED: 'TERMINATED'
};

export const EMPLOYMENT_TYPE = {
  FULL_TIME: 'FULL_TIME',
  PART_TIME: 'PART_TIME',
  CONTRACT: 'CONTRACT'
};

export const REWARD_TYPE = {
  MATERIAL: 'MATERIAL',
  MONEY: 'MONEY',
};

export const REWARD_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  CANCELLED: 'CANCELLED',
};

export const DISCIPLINE_TYPE = {
  LATE: 'LATE',
  ABSENT: 'ABSENT',
  VIOLATION: 'VIOLATION',
  FORGOTTEN_CHECKOUT: 'FORGOTTEN_CHECKOUT',
  OTHER: 'OTHER',
};

export const DISCIPLINE_STATUS = {
  RECORDED: 'RECORDED',
  APPROVED: 'APPROVED',
  WAIVED: 'WAIVED',
};
