import { useEffect, useState } from 'react'
import { adminService, type Employee } from '../services/adminService'

export default function Employees() {
  // ─── State: Employee List ───────────────────────────────────────────────
  const [employees, setEmployees] = useState<Employee[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [searchTerm, setSearchTerm] = useState('')

  // ─── State: Detail Modal ─────────────────────────────────────────────────
  const [showDetailModal, setShowDetailModal] = useState(false)
  const [detailEmployee, setDetailEmployee] = useState<Employee | null>(null)

  // ─── State: Create/Edit Modal ────────────────────────────────────────────
  const [showFormModal, setShowFormModal] = useState(false)
  const [formMode, setFormMode] = useState<'create' | 'edit'>('create')
  const [formLoading, setFormLoading] = useState(false)
  
  // Form fields
  const [formData, setFormData] = useState({
    employeeId: '',
    name: '',
    email: '',
    position: '',
    phone: '',
  })

  // ─── State: Delete ──────────────────────────────────────────────────────
  const [deletingEmployeeId, setDeletingEmployeeId] = useState<string | null>(null)


  // ─── Load Data ──────────────────────────────────────────────────────────
  useEffect(() => {
    loadEmployees()
  }, [])

  const loadEmployees = async () => {
    try {
      setLoading(true)
      const empData = await adminService.getAllEmployees()
      setEmployees(empData.employees || [])
    } catch (err: Error | unknown) {
      if (err instanceof Error) setError(err.message || 'Lỗi tải dữ liệu')
      else setError('Lỗi tải dữ liệu')
    } finally {
      setLoading(false)
    }
  }

  // ─── Computed Values ───────────────────────────────────────────────────
  const filteredEmployees = employees.filter(emp => {
    const matchesSearch =
      emp.name?.toLowerCase().includes(searchTerm.toLowerCase()) ||
      emp.email?.toLowerCase().includes(searchTerm.toLowerCase()) ||
      emp.employeeId?.toLowerCase().includes(searchTerm.toLowerCase())
    return matchesSearch
  })

  // ─── Modal: Detail Employee ─────────────────────────────────────────────
  const openDetailModal = (emp: Employee) => {
    setDetailEmployee(emp)
    setShowDetailModal(true)
  }

  const closeDetailModal = () => {
    setShowDetailModal(false)
    setDetailEmployee(null)
  }

  // ─── Modal: Create Employee ─────────────────────────────────────────────
  const openCreateModal = () => {
    setFormMode('create')
    setFormData({
      employeeId: '',
      name: '',
      email: '',
      position: '',
      phone: '',
    })
    setShowFormModal(true)
  }

  // ─── Modal: Edit Employee ───────────────────────────────────────────────
  const openEditModal = (emp: Employee) => {
    setFormMode('edit')
    setFormData({
      employeeId: emp.employeeId || '',
      name: emp.name || '',
      email: emp.email || '',
      position: emp.position || '',
      phone: emp.phone || '',
    })
    setDetailEmployee(emp)
    setShowFormModal(true)
    setShowDetailModal(false)
  }

  const closeFormModal = () => {
    setShowFormModal(false)
    setFormData({
      employeeId: '',
      name: '',
      email: '',
      position: '',
      phone: '',
    })
  }

  const handleFormChange = (field: string, value: string) => {
    setFormData(prev => ({ ...prev, [field]: value }))
  }

  // ─── Create/Edit Employee ───────────────────────────────────────────────
  const handleSaveEmployee = async (e: React.FormEvent) => {
    e.preventDefault()

    if (!formData.name.trim() || !formData.email.trim()) {
      alert('Vui lòng nhập tên và email')
      return
    }

    try {
      setFormLoading(true)
      if (formMode === 'create') {
        await adminService.createEmployee({
          // employeeId is auto-generated by Backend (like: EMP-001, EMP-002, ...)
          name: formData.name,
          email: formData.email,
          position: formData.position,
          phone: formData.phone,
        })
      } else if (formMode === 'edit' && detailEmployee) {
        await adminService.updateEmployee(detailEmployee._id, {
          name: formData.name,
          email: formData.email,
          position: formData.position,
          phone: formData.phone,
        })
      }
      
      await loadEmployees()
      closeFormModal()
    } catch (err: Error | unknown) {
      if (err instanceof Error) alert(err.message || 'Lỗi khi lưu nhân viên')
      else alert('Lỗi khi lưu nhân viên')
    } finally {
      setFormLoading(false)
    }
  }

  // ─── Delete Employee ────────────────────────────────────────────────────
  const handleDeleteEmployee = async (emp: Employee) => {
    if (!window.confirm(`Bạn có chắc muốn xóa nhân viên ${emp.name}?\n\nHành động này không thể hoàn tác.`)) {
      return
    }

    try {
      setDeletingEmployeeId(emp._id)
      await adminService.deleteEmployee(emp._id)
      await loadEmployees()
    } catch (err: Error | unknown) {
      if (err instanceof Error) alert(err.message || 'Lỗi khi xóa nhân viên')
      else alert('Lỗi khi xóa nhân viên')
    } finally {
      setDeletingEmployeeId(null)
    }
  }

  // ─── Loading ────────────────────────────────────────────────────────────
  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-gray-600">Đang tải...</div>
      </div>
    )
  }

  if (error) {
    return (
      <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded">
        {error}
      </div>
    )
  }

  return (
    <div className="space-y-6 p-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Quản Lý Nhân Viên</h1>
          <p className="text-sm text-gray-500 mt-1">
            Tổng: {employees.length} nhân viên
          </p>
        </div>
        <button
          onClick={openCreateModal}
          className="px-4 py-2 bg-blue-600 text-white rounded-lg font-medium hover:bg-blue-700 transition-colors cursor-pointer text-sm"
        >
          + Thêm Nhân Viên
        </button>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-2 gap-4">
        {[
          { label: 'Tổng Nhân Viên', value: employees.length, color: 'text-blue-600' },
          { label: 'Đã Phân Phòng', value: employees.filter(e => e.department && e.department !== 'N/A').length, color: 'text-green-600' },
        ].map(s => (
          <div key={s.label} className="bg-white rounded-lg border border-gray-200 p-4">
            <p className={`text-2xl font-bold ${s.color}`}>{s.value}</p>
            <p className="text-sm text-gray-500 mt-1">{s.label}</p>
          </div>
        ))}
      </div>

      {/* Search */}
      <div className="flex gap-3">
        <input
          type="text"
          placeholder="Tìm kiếm theo tên, email hoặc ID..."
          value={searchTerm}
          onChange={e => setSearchTerm(e.target.value)}
          className="flex-1 px-4 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
        />
      </div>

      {/* Employee Table */}
      <div className="bg-white rounded-lg border border-gray-200 overflow-hidden">
        <table className="w-full">
          <thead>
            <tr className="border-b border-gray-200 bg-gray-50">
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Mã NV</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Tên</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Email</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Chức Vụ</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Phòng Ban</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-700 uppercase tracking-wider">Thao Tác</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-200">
            {filteredEmployees.length === 0 ? (
              <tr>
                <td colSpan={6} className="px-6 py-4 text-center text-gray-400">
                  Không tìm thấy nhân viên nào
                </td>
              </tr>
            ) : (
              filteredEmployees.map(emp => (
                <tr key={emp._id} className="hover:bg-gray-50 transition-colors">
                  <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                    {emp.employeeId}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                    {emp.name}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    {emp.email}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                    {emp.position || '-'}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    {emp.department && emp.department !== 'N/A' ? (
                      <span className="px-2.5 py-1 bg-blue-100 text-blue-700 rounded-full text-xs font-semibold">
                        {emp.department}
                      </span>
                    ) : (
                      <span className="px-2.5 py-1 bg-gray-100 text-gray-700 rounded-full text-xs font-semibold">
                        Chưa phân phòng
                      </span>
                    )}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm space-x-2">
                    <button
                      onClick={() => openDetailModal(emp)}
                      className="px-3 py-1 rounded-md border border-blue-300 text-blue-600 hover:bg-blue-50 text-xs font-medium cursor-pointer"
                    >
                      Xem
                    </button>
                    <button
                      onClick={() => openEditModal(emp)}
                      className="px-3 py-1 rounded-md border border-green-300 text-green-600 hover:bg-green-50 text-xs font-medium cursor-pointer"
                    >
                      Sửa
                    </button>
                    <button
                      onClick={() => handleDeleteEmployee(emp)}
                      disabled={deletingEmployeeId === emp._id}
                      className="px-3 py-1 rounded-md border border-red-300 text-red-600 hover:bg-red-50 text-xs font-medium cursor-pointer disabled:opacity-50"
                    >
                      {deletingEmployeeId === emp._id ? 'Đang xóa...' : 'Xóa'}
                    </button>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      {/* ─── DETAIL MODAL ───────────────────────────────────────────────────── */}
      {showDetailModal && detailEmployee && (
        <div className="fixed inset-0 bg-black/40 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-2xl w-full max-w-md">
            <div className="p-6 border-b border-gray-200">
              <h2 className="text-xl font-bold text-gray-900">Thông Tin Nhân Viên</h2>
              <p className="text-sm text-gray-500 mt-1">{detailEmployee.name}</p>
            </div>

            <div className="p-6 space-y-4">
              <div>
                <label className="text-xs font-medium text-gray-500 uppercase tracking-wide">Mã Nhân Viên</label>
                <p className="text-sm text-gray-900">{detailEmployee.employeeId}</p>
              </div>
              <div>
                <label className="text-xs font-medium text-gray-500 uppercase tracking-wide">Email</label>
                <p className="text-sm text-gray-900">{detailEmployee.email}</p>
              </div>
              <div>
                <label className="text-xs font-medium text-gray-500 uppercase tracking-wide">Chức Vụ</label>
                <p className="text-sm text-gray-900">{detailEmployee.position || '-'}</p>
              </div>
              <div>
                <label className="text-xs font-medium text-gray-500 uppercase tracking-wide">Phone</label>
                <p className="text-sm text-gray-900">{detailEmployee.phone || '-'}</p>
              </div>
              <div>
                <label className="text-xs font-medium text-gray-500 uppercase tracking-wide">Phòng Ban</label>
                <p className="text-sm text-gray-900">
                  {detailEmployee.department && detailEmployee.department !== 'N/A'
                    ? detailEmployee.department
                    : 'Chưa phân phòng'}
                </p>
              </div>
            </div>

            <div className="p-6 border-t border-gray-200 flex gap-3">
              <button
                onClick={closeDetailModal}
                className="flex-1 px-4 py-2 border border-gray-300 rounded-lg text-gray-700 font-medium hover:bg-gray-50 transition-colors cursor-pointer"
              >
                Đóng
              </button>
              <button
                onClick={() => openEditModal(detailEmployee)}
                className="flex-1 px-4 py-2 bg-blue-600 text-white rounded-lg font-medium hover:bg-blue-700 cursor-pointer"
              >
                Chỉnh Sửa
              </button>
            </div>
          </div>
        </div>
      )}

      {/* ─── CREATE/EDIT MODAL ──────────────────────────────────────────────── */}
      {showFormModal && (
        <div className="fixed inset-0 bg-black/40 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-2xl w-full max-w-md">
            <div className="p-6 border-b border-gray-200">
              <h2 className="text-xl font-bold text-gray-900">
                {formMode === 'create' ? 'Thêm Nhân Viên Mới' : 'Chỉnh Sửa Nhân Viên'}
              </h2>
            </div>

            <form onSubmit={handleSaveEmployee} className="p-6 space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Tên Nhân Viên *
                </label>
                <input
                  type="text"
                  value={formData.name}
                  onChange={e => handleFormChange('name', e.target.value)}
                  placeholder="Nhập tên"
                  required
                  className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Email *
                </label>
                <input
                  type="email"
                  value={formData.email}
                  onChange={e => handleFormChange('email', e.target.value)}
                  placeholder="example@company.com"
                  required
                  className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Chức Vụ
                </label>
                <input
                  type="text"
                  value={formData.position}
                  onChange={e => handleFormChange('position', e.target.value)}
                  placeholder="VD: Kỹ sư"
                  className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Số Điện Thoại
                </label>
                <input
                  type="tel"
                  value={formData.phone}
                  onChange={e => handleFormChange('phone', e.target.value)}
                  placeholder="0123456789"
                  className="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>

              <div className="flex gap-3 pt-2">
                <button
                  type="button"
                  onClick={closeFormModal}
                  className="flex-1 px-4 py-2 border border-gray-300 rounded-lg text-gray-700 font-medium hover:bg-gray-50 transition-colors cursor-pointer"
                >
                  Hủy
                </button>
                <button
                  type="submit"
                  disabled={formLoading}
                  className="flex-1 px-4 py-2 bg-blue-600 text-white rounded-lg font-medium hover:bg-blue-700 disabled:opacity-50 cursor-pointer"
                >
                  {formLoading ? (formMode === 'create' ? 'Đang Thêm...' : 'Đang Lưu...') : (formMode === 'create' ? 'Thêm' : 'Lưu')}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  )
}
